// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace PersonAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("BusinessEntity")]
    public class BusinessEntityController : ControllerBase {
        
        private IBusinessEntityBuilder _builder;
        
        public BusinessEntityController(IBusinessEntityBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<BusinessEntityModel>> GetBusinessEntities() {

            return await _builder.GetBusinessEntities()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(BusinessEntityModel.BusinessEntityID));
            propNames.Add(nameof(BusinessEntityModel.Rowguid));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<BusinessEntityModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetBusinessEntities()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{businessEntityID}")]
        public async Task<ActionResult> GetBusinessEntity_ByBusinessEntityID(int businessEntityID) {

             var response = await _builder.GetBusinessEntity_ByBusinessEntityID(businessEntityID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddBusinessEntity([FromBody]BusinessEntityModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddBusinessEntity(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddBusinessEntity)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetBusinessEntity_ByBusinessEntityID", new {businessEntityID = ((BusinessEntityModel)response.Model).BusinessEntityID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateBusinessEntity([FromBody]BusinessEntityModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateBusinessEntity(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateBusinessEntity)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{businessEntityID}")]
        public async Task<ActionResult> DeleteBusinessEntity(int businessEntityID) {

            var response = await _builder.DeleteBusinessEntity(businessEntityID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteBusinessEntity)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

