// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace PersonAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("BusinessEntityContact")]
    public class BusinessEntityContactController : ControllerBase {
        
        private IBusinessEntityContactBuilder _builder;
        
        public BusinessEntityContactController(IBusinessEntityContactBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<BusinessEntityContactModel>> GetBusinessEntityContacts() {

            return await _builder.GetBusinessEntityContacts()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(BusinessEntityContactModel.BusinessEntityID));
            propNames.Add(nameof(BusinessEntityContactModel.PersonID));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<BusinessEntityContactModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetBusinessEntityContacts()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{businessEntityID}/{personID}/{contactTypeID}")]
        public async Task<ActionResult> GetBusinessEntityContact_ByBusinessEntityIDPersonIDContactTypeID(int businessEntityID, int personID, int contactTypeID) {

             var response = await _builder.GetBusinessEntityContact_ByBusinessEntityIDPersonIDContactTypeID(businessEntityID, personID, contactTypeID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpGet("GetBusinessEntityContact_ByBusinessEntityID/{businessEntityID}")]
        public async Task<IList<BusinessEntityContactModel>> GetBusinessEntityContact_ByBusinessEntityID(int businessEntityID) {

            return await _builder.GetBusinessEntityContact_ByBusinessEntityID(businessEntityID)?.ToListAsync();
        }
        
        [HttpGet("GetBusinessEntityContact_ByPersonID/{personID}")]
        public async Task<IList<BusinessEntityContactModel>> GetBusinessEntityContact_ByPersonID(int personID) {

            return await _builder.GetBusinessEntityContact_ByPersonID(personID)?.ToListAsync();
        }
        
        [HttpGet("GetBusinessEntityContact_ByContactTypeID/{contactTypeID}")]
        public async Task<IList<BusinessEntityContactModel>> GetBusinessEntityContact_ByContactTypeID(int contactTypeID) {

            return await _builder.GetBusinessEntityContact_ByContactTypeID(contactTypeID)?.ToListAsync();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddBusinessEntityContact([FromBody]BusinessEntityContactModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddBusinessEntityContact(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddBusinessEntityContact)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetBusinessEntityContact_ByBusinessEntityIDPersonIDContactTypeID", new {businessEntityID = ((BusinessEntityContactModel)response.Model).BusinessEntityID, personID = ((BusinessEntityContactModel)response.Model).PersonID, contactTypeID = ((BusinessEntityContactModel)response.Model).ContactTypeID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateBusinessEntityContact([FromBody]BusinessEntityContactModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateBusinessEntityContact(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateBusinessEntityContact)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{businessEntityID}/{personID}/{contactTypeID}")]
        public async Task<ActionResult> DeleteBusinessEntityContact(int businessEntityID, int personID, int contactTypeID) {

            var response = await _builder.DeleteBusinessEntityContact(businessEntityID, personID, contactTypeID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteBusinessEntityContact)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

