// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace PersonAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("ContactType")]
    public class ContactTypeController : ControllerBase {
        
        private IContactTypeBuilder _builder;
        
        public ContactTypeController(IContactTypeBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<ContactTypeModel>> GetContactTypes() {

            return await _builder.GetContactTypes()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(ContactTypeModel.ContactTypeID));
            propNames.Add(nameof(ContactTypeModel.Name));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<ContactTypeModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetContactTypes()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{contactTypeID}")]
        public async Task<ActionResult> GetContactType_ByContactTypeID(int contactTypeID) {

             var response = await _builder.GetContactType_ByContactTypeID(contactTypeID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddContactType([FromBody]ContactTypeModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddContactType(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddContactType)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetContactType_ByContactTypeID", new {contactTypeID = ((ContactTypeModel)response.Model).ContactTypeID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateContactType([FromBody]ContactTypeModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateContactType(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateContactType)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{contactTypeID}")]
        public async Task<ActionResult> DeleteContactType(int contactTypeID) {

            var response = await _builder.DeleteContactType(contactTypeID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteContactType)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

