// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace PersonAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("CountryRegion")]
    public class CountryRegionController : ControllerBase {
        
        private ICountryRegionBuilder _builder;
        
        public CountryRegionController(ICountryRegionBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<CountryRegionModel>> GetCountryRegions() {

            return await _builder.GetCountryRegions()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(CountryRegionModel.CountryRegionCode));
            propNames.Add(nameof(CountryRegionModel.Name));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<CountryRegionModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetCountryRegions()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{countryRegionCode}")]
        public async Task<ActionResult> GetCountryRegion_ByCountryRegionCode(string countryRegionCode) {

             var response = await _builder.GetCountryRegion_ByCountryRegionCode(countryRegionCode);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddCountryRegion([FromBody]CountryRegionModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddCountryRegion(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddCountryRegion)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetCountryRegion_ByCountryRegionCode", new {countryRegionCode = ((CountryRegionModel)response.Model).CountryRegionCode}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateCountryRegion([FromBody]CountryRegionModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateCountryRegion(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateCountryRegion)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{countryRegionCode}")]
        public async Task<ActionResult> DeleteCountryRegion(string countryRegionCode) {

            var response = await _builder.DeleteCountryRegion(countryRegionCode);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteCountryRegion)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

