// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace PersonAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("EmailAddress")]
    public class EmailAddressController : ControllerBase {
        
        private IEmailAddressBuilder _builder;
        
        public EmailAddressController(IEmailAddressBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<EmailAddressModel>> GetEmailAddresses() {

            return await _builder.GetEmailAddresses()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(EmailAddressModel.BusinessEntityID));
            propNames.Add(nameof(EmailAddressModel.EmailAddressID));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<EmailAddressModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetEmailAddresses()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{businessEntityID}/{emailAddressID}")]
        public async Task<ActionResult> GetEmailAddress_ByBusinessEntityIDEmailAddressID(int businessEntityID, int emailAddressID) {

             var response = await _builder.GetEmailAddress_ByBusinessEntityIDEmailAddressID(businessEntityID, emailAddressID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpGet("GetEmailAddress_ByBusinessEntityID/{businessEntityID}")]
        public async Task<IList<EmailAddressModel>> GetEmailAddress_ByBusinessEntityID(int businessEntityID) {

            return await _builder.GetEmailAddress_ByBusinessEntityID(businessEntityID)?.ToListAsync();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddEmailAddress([FromBody]EmailAddressModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddEmailAddress(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddEmailAddress)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetEmailAddress_ByBusinessEntityIDEmailAddressID", new {businessEntityID = ((EmailAddressModel)response.Model).BusinessEntityID, emailAddressID = ((EmailAddressModel)response.Model).EmailAddressID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateEmailAddress([FromBody]EmailAddressModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateEmailAddress(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateEmailAddress)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{businessEntityID}/{emailAddressID}")]
        public async Task<ActionResult> DeleteEmailAddress(int businessEntityID, int emailAddressID) {

            var response = await _builder.DeleteEmailAddress(businessEntityID, emailAddressID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteEmailAddress)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

