// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace PersonAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("Password")]
    public class PasswordController : ControllerBase {
        
        private IPasswordBuilder _builder;
        
        public PasswordController(IPasswordBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<PasswordModel>> GetPasswords() {

            return await _builder.GetPasswords()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(PasswordModel.BusinessEntityID));
            propNames.Add(nameof(PasswordModel.PasswordHash));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<PasswordModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetPasswords()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{businessEntityID}")]
        public async Task<ActionResult> GetPassword_ByBusinessEntityID(int businessEntityID) {

             var response = await _builder.GetPassword_ByBusinessEntityID(businessEntityID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddPassword([FromBody]PasswordModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddPassword(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddPassword)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetPassword_ByBusinessEntityID", new {businessEntityID = ((PasswordModel)response.Model).BusinessEntityID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdatePassword([FromBody]PasswordModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdatePassword(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdatePassword)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{businessEntityID}")]
        public async Task<ActionResult> DeletePassword(int businessEntityID) {

            var response = await _builder.DeletePassword(businessEntityID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeletePassword)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

