// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace PersonAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("PersonPhone")]
    public class PersonPhoneController : ControllerBase {
        
        private IPersonPhoneBuilder _builder;
        
        public PersonPhoneController(IPersonPhoneBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<PersonPhoneModel>> GetPersonPhones() {

            return await _builder.GetPersonPhones()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(PersonPhoneModel.BusinessEntityID));
            propNames.Add(nameof(PersonPhoneModel.PhoneNumber));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<PersonPhoneModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetPersonPhones()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{businessEntityID}/{phoneNumber}/{phoneNumberTypeID}")]
        public async Task<ActionResult> GetPersonPhone_ByBusinessEntityIDPhoneNumberPhoneNumberTypeID(int businessEntityID, string phoneNumber, int phoneNumberTypeID) {

             var response = await _builder.GetPersonPhone_ByBusinessEntityIDPhoneNumberPhoneNumberTypeID(businessEntityID, phoneNumber, phoneNumberTypeID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpGet("GetPersonPhone_ByBusinessEntityID/{businessEntityID}")]
        public async Task<IList<PersonPhoneModel>> GetPersonPhone_ByBusinessEntityID(int businessEntityID) {

            return await _builder.GetPersonPhone_ByBusinessEntityID(businessEntityID)?.ToListAsync();
        }
        
        [HttpGet("GetPersonPhone_ByPhoneNumberTypeID/{phoneNumberTypeID}")]
        public async Task<IList<PersonPhoneModel>> GetPersonPhone_ByPhoneNumberTypeID(int phoneNumberTypeID) {

            return await _builder.GetPersonPhone_ByPhoneNumberTypeID(phoneNumberTypeID)?.ToListAsync();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddPersonPhone([FromBody]PersonPhoneModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddPersonPhone(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddPersonPhone)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetPersonPhone_ByBusinessEntityIDPhoneNumberPhoneNumberTypeID", new {businessEntityID = ((PersonPhoneModel)response.Model).BusinessEntityID, phoneNumber = ((PersonPhoneModel)response.Model).PhoneNumber, phoneNumberTypeID = ((PersonPhoneModel)response.Model).PhoneNumberTypeID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdatePersonPhone([FromBody]PersonPhoneModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdatePersonPhone(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdatePersonPhone)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{businessEntityID}/{phoneNumber}/{phoneNumberTypeID}")]
        public async Task<ActionResult> DeletePersonPhone(int businessEntityID, string phoneNumber, int phoneNumberTypeID) {

            var response = await _builder.DeletePersonPhone(businessEntityID, phoneNumber, phoneNumberTypeID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeletePersonPhone)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

