// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace PersonAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("Person")]
    public class PersonController : ControllerBase {
        
        private IPersonBuilder _builder;
        
        public PersonController(IPersonBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<PersonModel>> GetPeople() {

            return await _builder.GetPeople()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(PersonModel.BusinessEntityID));
            propNames.Add(nameof(PersonModel.PersonType));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<PersonModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetPeople()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{businessEntityID}")]
        public async Task<ActionResult> GetPerson_ByBusinessEntityID(int businessEntityID) {

             var response = await _builder.GetPerson_ByBusinessEntityID(businessEntityID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddPerson([FromBody]PersonModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddPerson(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddPerson)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetPerson_ByBusinessEntityID", new {businessEntityID = ((PersonModel)response.Model).BusinessEntityID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdatePerson([FromBody]PersonModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdatePerson(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdatePerson)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{businessEntityID}")]
        public async Task<ActionResult> DeletePerson(int businessEntityID) {

            var response = await _builder.DeletePerson(businessEntityID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeletePerson)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

