// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace PersonAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("PhoneNumberType")]
    public class PhoneNumberTypeController : ControllerBase {
        
        private IPhoneNumberTypeBuilder _builder;
        
        public PhoneNumberTypeController(IPhoneNumberTypeBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<PhoneNumberTypeModel>> GetPhoneNumberTypes() {

            return await _builder.GetPhoneNumberTypes()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(PhoneNumberTypeModel.PhoneNumberTypeID));
            propNames.Add(nameof(PhoneNumberTypeModel.Name));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<PhoneNumberTypeModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetPhoneNumberTypes()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{phoneNumberTypeID}")]
        public async Task<ActionResult> GetPhoneNumberType_ByPhoneNumberTypeID(int phoneNumberTypeID) {

             var response = await _builder.GetPhoneNumberType_ByPhoneNumberTypeID(phoneNumberTypeID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddPhoneNumberType([FromBody]PhoneNumberTypeModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddPhoneNumberType(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddPhoneNumberType)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetPhoneNumberType_ByPhoneNumberTypeID", new {phoneNumberTypeID = ((PhoneNumberTypeModel)response.Model).PhoneNumberTypeID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdatePhoneNumberType([FromBody]PhoneNumberTypeModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdatePhoneNumberType(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdatePhoneNumberType)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{phoneNumberTypeID}")]
        public async Task<ActionResult> DeletePhoneNumberType(int phoneNumberTypeID) {

            var response = await _builder.DeletePhoneNumberType(phoneNumberTypeID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeletePhoneNumberType)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

