// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace PersonAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("StateProvince")]
    public class StateProvinceController : ControllerBase {
        
        private IStateProvinceBuilder _builder;
        
        public StateProvinceController(IStateProvinceBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<StateProvinceModel>> GetStateProvinces() {

            return await _builder.GetStateProvinces()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(StateProvinceModel.StateProvinceID));
            propNames.Add(nameof(StateProvinceModel.StateProvinceCode));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<StateProvinceModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetStateProvinces()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{stateProvinceID}")]
        public async Task<ActionResult> GetStateProvince_ByStateProvinceID(int stateProvinceID) {

             var response = await _builder.GetStateProvince_ByStateProvinceID(stateProvinceID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpGet("GetStateProvince_ByCountryRegionCode/{countryRegionCode}")]
        public async Task<IList<StateProvinceModel>> GetStateProvince_ByCountryRegionCode(string countryRegionCode) {

            return await _builder.GetStateProvince_ByCountryRegionCode(countryRegionCode)?.ToListAsync();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddStateProvince([FromBody]StateProvinceModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddStateProvince(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddStateProvince)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetStateProvince_ByStateProvinceID", new {stateProvinceID = ((StateProvinceModel)response.Model).StateProvinceID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateStateProvince([FromBody]StateProvinceModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateStateProvince(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateStateProvince)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{stateProvinceID}")]
        public async Task<ActionResult> DeleteStateProvince(int stateProvinceID) {

            var response = await _builder.DeleteStateProvince(stateProvinceID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteStateProvince)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

