// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Entities;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace PersonAPI.Services {
    
    
    public class AddressBuilder : IAddressBuilder {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public AddressBuilder(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        private Expression<Func<Address, AddressModel>>  ProjectToModel {
            get {
                return entity => _mapper.Map<AddressModel>(entity);
            }
        }
        
        public IQueryable<AddressModel> GetAddresses() {
            return _entities.Addresses.Select(ProjectToModel);
        }
        
        public IList<ExpandoObject> GetDisplayModels(List<string> propNames) {
            var models = _entities.Addresses.Select(ProjectToModel);

            var displayModels = new List<ExpandoObject>();
            foreach (var model in models)
            {
                dynamic displayModel = DynamicHelper.ConvertToExpando(model, propNames);
                displayModels.Add(displayModel);
            }

            return displayModels;
        }
        
        public async Task<BuilderResponse> GetAddress_ByAddressID(int addressID) {
          var query = await Search(_entities.Addresses, x => x.AddressID == addressID).Select(ProjectToModel)?.ToListAsync();
            if (query.Any()) {
              return new BuilderResponse{ Model = query.Single() }; 
            }
            else {
           return new BuilderResponse { RequestMessage = $"Record Not Found; Address with addressID = '{addressID}' doesn't exist." }; 
            }
        }
        
        public IQueryable<AddressModel> GetAddress_ByStateProvinceID(int stateProvinceID) {

          var query = Search(_entities.Addresses, x => x.StateProvinceID == stateProvinceID).Select(ProjectToModel);

            return query;
        }
        
        public async Task<BuilderResponse> AddAddress(AddressModel model) {
            var matchStateProvinceID = _entities.StateProvinces.Where(x => x.StateProvinceID.Equals(model.StateProvinceID));
            if (!matchStateProvinceID.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.StateProvinceID) + " '{model.StateProvinceID}' doesn't exist in the system."}; 
            }

           try
           {
                 var entity = _mapper.Map<Address>(model);
                _entities.Addresses.Add(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("Address added with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ Model = new AddressModel(entity) }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert explicit value for identity column"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "IDENTITY_INSERT is set to OFF; Cannot insert explicit value for identity column when IDENTITY_INSERT is set to OFF."};
                }
                else if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> UpdateAddress(AddressModel model) {

          var query = Search(_entities.Addresses, x =>  x.AddressID == model.AddressID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("Address with _addressID = '{0}' doesn't exist.",model.AddressID)}; 
            }
            var matchStateProvinceID = _entities.StateProvinces.Where(x => x.StateProvinceID.Equals(model.StateProvinceID));
            if (!matchStateProvinceID.Any()) {
              return new BuilderResponse{ RequestMessage = "Foreign Key Violation; " + nameof(model.StateProvinceID) + string.Format("Address with StateProvinceID = '{0}' doesn't exist.", model.StateProvinceID)}; 
            }

           try
           {
            Address entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("Address update with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.Created }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> DeleteAddress(int addressID) {
          var query = Search(_entities.Addresses, x => x.AddressID == addressID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("Address with _addressID = '{0}' doesn't exist.",addressID)}; 
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.Addresses.Remove(entity);
               await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("Address deleted with values: '{0}'", JsonConvert.SerializeObject(new AddressModel(entity))));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.NoContent }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("The DELETE statement conflicted with the REFERENCE constraint"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Please delete related items first."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        private IQueryable<Address> Search(IQueryable<Address> query, Expression<Func<Address, bool>> filter) {
            return query.Where(filter);
        }
    }
}

