// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PersonAPI.Models {
    
    
    [Table("BuilderResponse")]
    public partial class BuilderResponse {
        
        // validation messages
        public string RequestMessage;
        
        // HttpStatusCode
        public int StatusCode;
        
        // model crated or updated
        public object Model;
        
        // catch error
        public string ErrorMessage;
    }
}

