// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Entities;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace PersonAPI.Services {
    
    
    public class BusinessEntityContactBuilder : IBusinessEntityContactBuilder {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public BusinessEntityContactBuilder(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        private Expression<Func<BusinessEntityContact, BusinessEntityContactModel>>  ProjectToModel {
            get {
                return entity => _mapper.Map<BusinessEntityContactModel>(entity);
            }
        }
        
        public IQueryable<BusinessEntityContactModel> GetBusinessEntityContacts() {
            return _entities.BusinessEntityContacts.Select(ProjectToModel);
        }
        
        public IList<ExpandoObject> GetDisplayModels(List<string> propNames) {
            var models = _entities.BusinessEntityContacts.Select(ProjectToModel);

            var displayModels = new List<ExpandoObject>();
            foreach (var model in models)
            {
                dynamic displayModel = DynamicHelper.ConvertToExpando(model, propNames);
                displayModels.Add(displayModel);
            }

            return displayModels;
        }
        
        public async Task<BuilderResponse> GetBusinessEntityContact_ByBusinessEntityIDPersonIDContactTypeID(int businessEntityID, int personID, int contactTypeID) {
          var query = await Search(_entities.BusinessEntityContacts, x => x.BusinessEntityID == businessEntityID&& x.PersonID == personID&& x.ContactTypeID == contactTypeID).Select(ProjectToModel)?.ToListAsync();
            if (query.Any()) {
              return new BuilderResponse{ Model = query.Single() }; 
            }
            else {
           return new BuilderResponse { RequestMessage = $"Record Not Found; BusinessEntityContact with businessEntityID, personID, contactTypeID = '{businessEntityID}', '{personID}', '{contactTypeID}' doesn't exist." }; 
            }
        }
        
        public IQueryable<BusinessEntityContactModel> GetBusinessEntityContact_ByBusinessEntityID(int businessEntityID) {

          var query = Search(_entities.BusinessEntityContacts, x => x.BusinessEntityID == businessEntityID).Select(ProjectToModel);

            return query;
        }
        
        public IQueryable<BusinessEntityContactModel> GetBusinessEntityContact_ByPersonID(int personID) {

          var query = Search(_entities.BusinessEntityContacts, x => x.PersonID == personID).Select(ProjectToModel);

            return query;
        }
        
        public IQueryable<BusinessEntityContactModel> GetBusinessEntityContact_ByContactTypeID(int contactTypeID) {

          var query = Search(_entities.BusinessEntityContacts, x => x.ContactTypeID == contactTypeID).Select(ProjectToModel);

            return query;
        }
        
        public async Task<BuilderResponse> AddBusinessEntityContact(BusinessEntityContactModel model) {
            var matchBusinessEntityID = _entities.BusinessEntities.Where(x => x.BusinessEntityID.Equals(model.BusinessEntityID));
            if (!matchBusinessEntityID.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.BusinessEntityID) + " '{model.BusinessEntityID}' doesn't exist in the system."}; 
            }

            var matchPersonID = _entities.People.Where(x => x.BusinessEntityID.Equals(model.PersonID));
            if (!matchPersonID.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.PersonID) + " '{model.PersonID}' doesn't exist in the system."}; 
            }

            var matchContactTypeID = _entities.ContactTypes.Where(x => x.ContactTypeID.Equals(model.ContactTypeID));
            if (!matchContactTypeID.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.ContactTypeID) + " '{model.ContactTypeID}' doesn't exist in the system."}; 
            }

           try
           {
                 var entity = _mapper.Map<BusinessEntityContact>(model);
                _entities.BusinessEntityContacts.Add(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("BusinessEntityContact added with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ Model = new BusinessEntityContactModel(entity) }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert explicit value for identity column"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "IDENTITY_INSERT is set to OFF; Cannot insert explicit value for identity column when IDENTITY_INSERT is set to OFF."};
                }
                else if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> UpdateBusinessEntityContact(BusinessEntityContactModel model) {

          var query = Search(_entities.BusinessEntityContacts, x =>  x.BusinessEntityID == model.BusinessEntityID && x.PersonID == model.PersonID && x.ContactTypeID == model.ContactTypeID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("BusinessEntityContact with _businessEntityID, _personID, _contactTypeID = '{0}', '{1}', '{2}' doesn't exist.",model.BusinessEntityID, model.PersonID, model.ContactTypeID)}; 
            }
            var matchBusinessEntityID = _entities.BusinessEntities.Where(x => x.BusinessEntityID.Equals(model.BusinessEntityID));
            if (!matchBusinessEntityID.Any()) {
              return new BuilderResponse { RequestMessage = "Foreign Key Violation; " + nameof(model.BusinessEntityID) + string.Format("BusinessEntityID = '{0}' doesn't exist in the system.", model.BusinessEntityID)}; 
            }

            var matchPersonID = _entities.People.Where(x => x.BusinessEntityID.Equals(model.PersonID));
            if (!matchPersonID.Any()) {
              return new BuilderResponse { RequestMessage = "Foreign Key Violation; " + nameof(model.PersonID) + string.Format("PersonID = '{0}' doesn't exist in the system.", model.PersonID)}; 
            }

            var matchContactTypeID = _entities.ContactTypes.Where(x => x.ContactTypeID.Equals(model.ContactTypeID));
            if (!matchContactTypeID.Any()) {
              return new BuilderResponse { RequestMessage = "Foreign Key Violation; " + nameof(model.ContactTypeID) + string.Format("ContactTypeID = '{0}' doesn't exist in the system.", model.ContactTypeID)}; 
            }

           try
           {
            BusinessEntityContact entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("BusinessEntityContact update with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.Created }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> DeleteBusinessEntityContact(int businessEntityID, int personID, int contactTypeID) {
          var query = Search(_entities.BusinessEntityContacts, x => x.BusinessEntityID == businessEntityID&& x.PersonID == personID&& x.ContactTypeID == contactTypeID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("BusinessEntityContact with _businessEntityID, _personID, _contactTypeID = '{0}', '{1}', '{2}' doesn't exist.",businessEntityID, personID, contactTypeID)}; 
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.BusinessEntityContacts.Remove(entity);
               await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("BusinessEntityContact deleted with values: '{0}'", JsonConvert.SerializeObject(new BusinessEntityContactModel(entity))));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.NoContent }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("The DELETE statement conflicted with the REFERENCE constraint"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Please delete related items first."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        private IQueryable<BusinessEntityContact> Search(IQueryable<BusinessEntityContact> query, Expression<Func<BusinessEntityContact, bool>> filter) {
            return query.Where(filter);
        }
    }
}

