// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using PersonAPI.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace PersonAPI.Services {
    
    
    public interface IAddressBuilder {
        
        IQueryable<AddressModel> GetAddresses();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetAddress_ByAddressID(int addressID);
        
        IQueryable<AddressModel> GetAddress_ByStateProvinceID(int stateProvinceID);
        
        Task<BuilderResponse> AddAddress(AddressModel model);
        
        Task<BuilderResponse> UpdateAddress(AddressModel model);
        
        Task<BuilderResponse> DeleteAddress(int addressID);
    }
}

