// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using PersonAPI.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace PersonAPI.Services {
    
    
    public interface IBusinessEntityAddressBuilder {
        
        IQueryable<BusinessEntityAddressModel> GetBusinessEntityAddresses();
        
        IList<ExpandoObject> GetDisplayModels(List<string> propNames);
        
        Task<BuilderResponse> GetBusinessEntityAddress_ByBusinessEntityIDAddressIDAddressTypeID(int businessEntityID, int addressID, int addressTypeID);
        
        IQueryable<BusinessEntityAddressModel> GetBusinessEntityAddress_ByBusinessEntityID(int businessEntityID);
        
        IQueryable<BusinessEntityAddressModel> GetBusinessEntityAddress_ByAddressID(int addressID);
        
        IQueryable<BusinessEntityAddressModel> GetBusinessEntityAddress_ByAddressTypeID(int addressTypeID);
        
        Task<BuilderResponse> AddBusinessEntityAddress(BusinessEntityAddressModel model);
        
        Task<BuilderResponse> UpdateBusinessEntityAddress(BusinessEntityAddressModel model);
        
        Task<BuilderResponse> DeleteBusinessEntityAddress(int businessEntityID, int addressID, int addressTypeID);
    }
}

