// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PersonAPI.Entities;
using PersonAPI.Models;
using PersonAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace PersonAPI.Services {
    
    
    public class StateProvinceBuilder : IStateProvinceBuilder {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public StateProvinceBuilder(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        private Expression<Func<StateProvince, StateProvinceModel>>  ProjectToModel {
            get {
                return entity => _mapper.Map<StateProvinceModel>(entity);
            }
        }
        
        public IQueryable<StateProvinceModel> GetStateProvinces() {
            return _entities.StateProvinces.Select(ProjectToModel);
        }
        
        public IList<ExpandoObject> GetDisplayModels(List<string> propNames) {
            var models = _entities.StateProvinces.Select(ProjectToModel);

            var displayModels = new List<ExpandoObject>();
            foreach (var model in models)
            {
                dynamic displayModel = DynamicHelper.ConvertToExpando(model, propNames);
                displayModels.Add(displayModel);
            }

            return displayModels;
        }
        
        public async Task<BuilderResponse> GetStateProvince_ByStateProvinceID(int stateProvinceID) {
          var query = await Search(_entities.StateProvinces, x => x.StateProvinceID == stateProvinceID).Select(ProjectToModel)?.ToListAsync();
            if (query.Any()) {
              return new BuilderResponse{ Model = query.Single() }; 
            }
            else {
           return new BuilderResponse { RequestMessage = $"Record Not Found; StateProvince with stateProvinceID = '{stateProvinceID}' doesn't exist." }; 
            }
        }
        
        public IQueryable<StateProvinceModel> GetStateProvince_ByCountryRegionCode(string countryRegionCode) {

          var query = Search(_entities.StateProvinces, x => x.CountryRegionCode == countryRegionCode).Select(ProjectToModel);

            return query;
        }
        
        public async Task<BuilderResponse> AddStateProvince(StateProvinceModel model) {
            var matchCountryRegionCode = _entities.CountryRegions.Where(x => x.CountryRegionCode.Equals(model.CountryRegionCode));
            if (!matchCountryRegionCode.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.CountryRegionCode) + " '{model.CountryRegionCode}' doesn't exist in the system."}; 
            }

           try
           {
                 var entity = _mapper.Map<StateProvince>(model);
                _entities.StateProvinces.Add(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("StateProvince added with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ Model = new StateProvinceModel(entity) }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert explicit value for identity column"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "IDENTITY_INSERT is set to OFF; Cannot insert explicit value for identity column when IDENTITY_INSERT is set to OFF."};
                }
                else if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> UpdateStateProvince(StateProvinceModel model) {

          var query = Search(_entities.StateProvinces, x =>  x.StateProvinceID == model.StateProvinceID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("StateProvince with _stateProvinceID = '{0}' doesn't exist.",model.StateProvinceID)}; 
            }
            var matchCountryRegionCode = _entities.CountryRegions.Where(x => x.CountryRegionCode.Equals(model.CountryRegionCode));
            if (!matchCountryRegionCode.Any()) {
              return new BuilderResponse{ RequestMessage = "Foreign Key Violation; " + nameof(model.CountryRegionCode) + string.Format("StateProvince with CountryRegionCode = '{0}' doesn't exist.", model.CountryRegionCode)}; 
            }

           try
           {
            StateProvince entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("StateProvince update with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.Created }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> DeleteStateProvince(int stateProvinceID) {
          var query = Search(_entities.StateProvinces, x => x.StateProvinceID == stateProvinceID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("StateProvince with _stateProvinceID = '{0}' doesn't exist.",stateProvinceID)}; 
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.StateProvinces.Remove(entity);
               await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("StateProvince deleted with values: '{0}'", JsonConvert.SerializeObject(new StateProvinceModel(entity))));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.NoContent }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("The DELETE statement conflicted with the REFERENCE constraint"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Please delete related items first."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        private IQueryable<StateProvince> Search(IQueryable<StateProvince> query, Expression<Func<StateProvince, bool>> filter) {
            return query.Where(filter);
        }
    }
}

