// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using PersonAPI.Entities;

namespace PersonAPI.Models {
    
    
    public class AutoMapperProfiles : Profile {
        
        public AutoMapperProfiles() {
            CreateMap<Address, AddressModel>();
            CreateMap<AddressModel, Address>();
            CreateMap<AddressType, AddressTypeModel>();
            CreateMap<AddressTypeModel, AddressType>();
            CreateMap<BusinessEntity, BusinessEntityModel>();
            CreateMap<BusinessEntityModel, BusinessEntity>();
            CreateMap<BusinessEntityAddress, BusinessEntityAddressModel>();
            CreateMap<BusinessEntityAddressModel, BusinessEntityAddress>();
            CreateMap<BusinessEntityContact, BusinessEntityContactModel>();
            CreateMap<BusinessEntityContactModel, BusinessEntityContact>();
            CreateMap<ContactType, ContactTypeModel>();
            CreateMap<ContactTypeModel, ContactType>();
            CreateMap<CountryRegion, CountryRegionModel>();
            CreateMap<CountryRegionModel, CountryRegion>();
            CreateMap<EmailAddress, EmailAddressModel>();
            CreateMap<EmailAddressModel, EmailAddress>();
            CreateMap<Password, PasswordModel>();
            CreateMap<PasswordModel, Password>();
            CreateMap<Person, PersonModel>();
            CreateMap<PersonModel, Person>();
            CreateMap<PersonPhone, PersonPhoneModel>();
            CreateMap<PersonPhoneModel, PersonPhone>();
            CreateMap<PhoneNumberType, PhoneNumberTypeModel>();
            CreateMap<PhoneNumberTypeModel, PhoneNumberType>();
            CreateMap<StateProvince, StateProvinceModel>();
            CreateMap<StateProvinceModel, StateProvince>();
        }
    }
}

